 
// Commands (ID_* and IDM_*) 
#define HID__REMOVE_REMARKS                     0x10000
#define HID__OPENFILE                           0x10083
#define HID_LIGHTSCRIBE_PANE                    0x10083
#define HID__BEMERKUNGENL                       0x10084
#define HID_LIGHTSCRIBE_PROGRESS                0x10084
#define HID__REMOVEREMARKS                      0x10085
#define HID_LIGHTSCRIBE_TIME_LEFT               0x10085
#define HID__SELECTTRANSPARENTCOLOR             0x1008C
#define HID__RAISE                              0x1008D
#define HID__LOWER                              0x1008E
#define HID__BRINGTOFRONT                       0x1008F
#define HID__SENDTOBACK                         0x10090
#define HID__DELETE                             0x10091
#define HID_SEARCH                              0x10093
#define HID__RAISE147                           0x10093
#define HID_ASSIGNTO                            0x10094
#define HID__LOWER148                           0x10094
#define HID__BRINGTOFRONT149                    0x10095
#define HID__SENDTOBACK150                      0x10096
#define HID__DELETE151                          0x10097
#define HID__STRETCHTOFULLCOVERSIZE             0x10098
#define HID__ALIGN                              0x10099
#define HID_ALIGN_TOPLEFT                       0x1009A
#define HID_ALIGN_TOPMIDDLE                     0x1009B
#define HID_ALIGN_TOPRIGHT                      0x1009C
#define HID_ALIGN_MIDDLELEFT                    0x1009D
#define HID_ALIGN_MIDDLEMIDDLE                  0x1009E
#define HID_ALIGN_MIDDLERIGHT                   0x1009F
#define HID_ALIGN_BOTTOMLEFT                    0x100A0
#define HID_ALIGN_BOTTOMMIDDLE                  0x100A1
#define HID_ALIGN_BOTTOMRIGHT                   0x100A2
#define HID_NEW_DATACD                          0x100A4
#define HID_NEU_DATEN                           0x100A5
#define HID_NEW_DATACD166                       0x100A6
#define HID_NEU_DATEN167                        0x100A7
#define HID_TOOLS_ADDTEXT168                    0x100A8
#define HID_TOOLS_ADDIMAGE169                   0x100A9
#define HID_TOOLS_SELECTBACKGROUNDIMAGE         0x100AA
#define HID_TOOLS_SCANBACKGROUNDIMAGE           0x100AB
#define HID_HELP_CDCOVERCREATORONTHEWEB         0x100B0
#define HID_HILFE_CDCOVERCREATORONTHEWEB        0x100B1
#define HID_HELP_CDCOVERCREATORONTHEWEB178      0x100B2
#define HID_HILFE_CDCOVERCREATORONTHEWEB179     0x100B3
#define HID__MATCHMERGE                         0x100B8
#define HID__COPYTRACKLISTINGTOCLIPBOARD        0x100B9
#define HID__EXPORTTRACKLISTINGASHTML           0x100BA
#define HID__REMOVEREMARKS194                   0x100C2
#define HID__BEMERKUNGENENTFERNEN               0x100C3
#define HID__ADJUSTCOLORS                       0x100C5
#define HID_                                    0x100C6
#define HID_199                                 0x100C7
#define HID_200                                 0x100C8
#define HID_X                                   0x100C9
#define HID_VIEW_TEXTTOOLBAR                    0x100CC
#define HID_FENSTER_N                           0x100CF
#define HID_FENSTER_VORHERIGESFENSTER           0x100D0
#define HID__BACKGROUNDIMAGE                    0x100D1
#define HID_BACKGROUNDIMAGE_TILE                0x100D2
#define HID_BACKGROUNDIMAGE_EDIT                0x100D3
#define HID_BACKGROUNDIMAGE_RELOAD              0x100D4
#define HID__EDITIMAGE                          0x100D6
#define HID__RELOADIMAGE                        0x100D7
#define HID_GRADIENT_LINEAR                     0x100DB
#define HID_GRADIENT_RECTANGULAR                0x100DC
#define HID_GRADIENT_DIAMOND                    0x100DD
#define HID_GRADIENT_RADIAL                     0x100DE
#define HID_GRADIENT_TRIANGULAR                 0x100DF
#define HID_GRADIENT_RADIALTOP                  0x100E0
#define HID_GRADIENT_WHEEL                      0x100E1
#define HID_WINDOW_NEXTWINDOW                   0x102BD
#define HID_WINDOW_PREVIOUSWINDOW               0x102BE
#define HID_BUTTON_MINIMIZE                     0x17F58
#define HID_BUTTON_RESTORE                      0x17F59
#define HID_BUTTON_CLOSE                        0x17F5A
#define HID_ADDGROUPING                         0x18003
#define HID_DELETEGROUPING                      0x18004
#define HID_TOOLS_ADDIMAGE                      0x18004
#define HID_PROPERTIES                          0x18005
#define HID_STYLETEMPLATE                       0x18006
#define HID_ZOOMOUT                             0x18007
#define HID_ZOOMIN                              0x18008
#define HID_TOOLS_ADDTEXT                       0x18009
#define HID_SHOWINLAY                           0x18010
#define HID_SHOWCOVER                           0x18012
#define HID_SHOWLABEL                           0x18015
#define HID_SHOWBACK                            0x18016
#define HID_DELETETRACK                         0x18017
#define HID_FILE_PROGRAMOPTIONS                 0x18018
#define HID_CHECKVERSION                        0x18019
#define HID_BKIMG_SCAN                          0x1801A
#define HID_BKIMG_LISTWEB                       0x1801B
#define HID_BKIMG_SEARCHWEB                     0x1801C
#define HID_BKIMG_IMAGE                         0x1801D
#define HID_FILE_NEW_EMPTYPROJECT               0x1801E
#define HID_FILE_SAVE_AS_IMAGE                  0x18093
#define HID_FILE_NEW_WIZARD                     0x1801F
#define HID_FILE_NEW_LISTWEB                    0x18022
#define HID_FILE_NEW_SEARCHWEB                  0x18023
#define HID_SHOWBOOKLET                         0x18025
#define HID_BROWSE_SEARCH                       0x18026
#define HID_BROWSE_APPLY                        0x18027
#define HID_BROWSE_LIST                         0x18028
#define HID_VIEW_STYLES                         0x18029
#define HID_ANSICHT_COVERBROWSER                0x1802A
#define HID_VIEW_COVERBROWSER                   0x1802B
#define HID_BROWSE_IMAGE                        0x1802C
#define HID_BROWSE_BKTEXTURE                    0x1802E
#define HID_BROWSE_BKALPHA                      0x1802F
#define HID_BROWSE_WEB                          0x18030
#define HID_VIEW_LEFTPANEL                      0x18032
#define HID_VIEW_LYRICSBROWSER                  0x18033
#define HID_LBROWSE_SEARCH                      0x18035
#define HID_LBROWSE_LIST                        0x18036
#define HID_RTFF_BOLD                           0x18037
#define HID_RTFF_ITALIC                         0x18038
#define HID_RTFF_UNDERLINE                      0x18039
#define HID_RTFF_ALIGNLEFT                      0x1803A
#define HID_RTFF_ALIGNCENTER                    0x1803B
#define HID_RTFF_ALIGNRIGHT                     0x1803C
#define HID_RTFF_STRIKETHRU                     0x1803E
#define HID_RTFF_SUP                            0x1803F
#define HID_RTFF_SUB                            0x18040
#define HID_RTFF_FONT                           0x18041
#define HID_RTFF_FONTSIZE                       0x18042
#define HID_RTFF_COLOR                          0x18043
#define HID_RTFF_UNDERLINE_DOT                  0x18044
#define HID_RTFF_BKCOLOR                        0x18046
#define HID_RTFF_BULLETS                        0x1804A
#define HID_RTFF_BORDER                         0x1804B
#define HID_RTFF_PAGEBREAK                      0x1804C
#define HID_FILE_NEW_IMPORTM3U                  0x1804D
#define HID_RTFF_BORDER_LEFT                    0x18051
#define HID_RTFF_BORDER_RIGHT                   0x18052
#define HID_RTFF_BORDER_TOP                     0x18053
#define HID_RTFF_BORDER_BOTTOM                  0x18054
#define HID_RTFF_BORDER_INSIDE                  0x18055
#define HID_RTFF_BORDER_OUTSIDE                 0x18056
#define HID_RTFF_BULLETS_NONE                   0x18057
#define HID_RTFF_BULLETS_BULLET                 0x18058
#define HID_RTFF_BULLETS_123                    0x18059
#define HID_RTFF_BULLETS_LOWER                  0x1805A
#define HID_RTFF_BULLETS_UPPER                  0x1805B
#define HID_RTFF_BULLETS_ROMLOWER               0x1805C
#define HID_RTFF_BULLETS_ROMUPPER               0x1805D
#define HID_TOOLS_ADDBARCODE                    0x18085
#define HID__BARCODEPROPERTIES                  0x1808E
#define HID_FILE_LIGHTSCRIBE                    0x180E8
#define HID_FILE_PRINT2                         0x1E108
#define HID_FILE_PRINT_PREVIEW2                 0x1E10A
#define HID_FILE_PRINT3                         0x1E10B
#define HID_FILE_PRINT_PREVIEW3                 0x1E10C
 
// Prompts (IDP_*) 
#define HIDP_OLE_INIT_FAILED                    0x30064
 
// Resources (IDR_*) 
#define HIDR_MANIFEST                           0x20001
#define HIDR_POPUP_LABELITVIEW                  0x20070
#define HIDR_HTML_DLGABOUT                      0x2007F
#define HIDR_MAINFRAME                          0x20080
#define HIDR_CdCoverCreatorTYPE                 0x20081
#define HIDR_LABELSTYPE                         0x20081
#define HIDR_MENU_OPEN                          0x20082
#define HIDR_RAINBOW                            0x20086
#define HIDR_MENU_FLOATINGIMAGE                 0x2008B
#define HIDR_MENU_TRACK                         0x2008F
#define HIDR_MENU_SEP                           0x20090
#define HIDR_MENU_FLOATINGTEXT                  0x20092
#define HIDR_AVIFIND                            0x200A5
#define HIDR_TOOLBAR_GRP                        0x200A9
#define HIDR_MENU1                              0x200B7
#define HIDR_MENU_CWSPECIALFUNCTIONS            0x200B7
#define HIDR_JPEG_SPLASHSCREEN                  0x200BD
#define HIDR_JPEG_SPLASHSCREEN_PF               0x200BE
#define HIDR_JPEG_ABOUTBK                       0x200C0
#define HIDR_JPEG_PAYPAL                        0x200C1
#define HIDR_TOOLBAR2                           0x200CA
#define HIDR_TOOLBAR_WINDOW                     0x200CA
#define HIDR_TOOLBAR_NEW                        0x200CE
#define HIDR_TOOLBAR_BROWSE                     0x200D6
#define HIDR_MENU_GRADIENT                      0x200DA
#define HIDR_HTML_EMPTY                         0x200DB
#define HIDR_MENU_FLOATINGBARCODE               0x200E1
#define HIDR_TOOLBAR_LYRICSBROWSER              0x200E3
#define HIDR_COVERBROWSER                       0x200E6
#define HIDR_LYRICSBROWSER                      0x200E7
#define HIDR_TOOLBAR_RTFFORMAT                  0x200EC
#define HIDR_TOOLBAR1                           0x20100
#define HIDR_MENU_RTF_BORDER                    0x20102
#define HIDR_MENU_RTF_BULLETS                   0x20103
#define HIDR_TOOLBAR_RTF_BORDER                 0x20104
#define HIDR_TOOLBAR_RTF_BULLETS                0x20106
 
// Dialogs (IDD_*) 
#define HIDD_ABOUTBOX                           0x20064
#define HIDD_DIALOG_COVERSLIST                  0x20066
#define HIDD_PROPPAGE1                          0x20067
#define HIDD_DIALOGBAR_MEDIUM                   0x20067
#define HIDD_PROPPAGE2                          0x20068
#define HIDD_PROPPAGE11                         0x2006D
#define HIDD_PROPPAGE21                         0x2006E
#define HIDD_PROPPAGE31                         0x2006F
#define HIDD_PROPPAGE13                         0x2007A
#define HIDD_PROPPAGE_PS_HOSTS                  0x2007A
#define HIDD_PROPPAGE23                         0x2007B
#define HIDD_PROPPAGE_PS_VERSIONCHECKING        0x2007B
#define HIDD_PROPPAGE32                         0x2007C
#define HIDD_PROPPAGE_PS_PRINTERSETTINGS        0x2007C
#define HIDD_DIALOG_COVERSSEARCH                0x20081
#define HIDD_DIALOG_SELECTLABELS                0x20087
#define HIDD_PAGESETUPDLG_PF                    0x2008A
#define HIDD_PROPPAGE3                          0x2008C
#define HIDD_PROPPAGE01                         0x20096
#define HIDD_DIALOG_PICKTITLE                   0x2009C
#define HIDD_PROPPAGE_CW_CREATEDATACD           0x200A3
#define HIDD_DIALOG_PRINTTEMPLATE               0x200A7
#define HIDD_DIALOG_MATCHMERGE                  0x200AB
#define HIDD_PROPPAGE20                         0x200AC
#define HIDD_PROPPAGE22                         0x200AD
#define HIDD_PROPPAGE10                         0x200AE
#define HIDD_DIALOG_ABOUT_PF                    0x200AE
#define HIDD_DIALOG_PICKDRIVE                   0x200B2
#define HIDD_PAGESETUPDLG                       0x200B3
#define HIDD_DIALOG_STYLESPINES                 0x200B5
#define HIDD_PROPPAGE12                         0x200B9
#define HIDD_DIALOG_ABOUT                       0x200BF
#define HIDD_DIALOG_IMAGEPROPERTIES             0x200C4
#define HIDD_DIALOG_PROGSETTINGS                0x200C6
#define HIDD_DIALOG_UPDATE                      0x200C7
#define HIDD_DIALOG_PRINTTESTCANCEL             0x200C9
#define HIDD_DIALOG_STYLE                       0x200D0
#define HIDD_LEFTPANEL                          0x200D1
#define HIDD_DIALOG1                            0x200D5
#define HIDD_PROPPAGE_PS_IMAGEEDITING           0x200D5
#define HIDD_DIALOG_SETIMAGEEDITOR              0x200D8
#define HIDD_DIALOG_ROLLUP                      0x200DF
#define HIDD_DIALOG_STYLEBKIMG                  0x200E0
#define HIDD_DIALOG_STYLEALPHA                  0x200E1
#define HIDD_DIALOG_BARCODEPROPS                0x200E2
#define HIDD_DIALOG_LIGHTSCRIBE                 0x200E4
#define HIDD_DIALOG_STYLEFONTS                  0x200EF
#define HIDD_FILEOPENPREVIEW                    0x200F0
#define HIDD_PROPPAGE_STW_CHOOSETITLEFONTS      0x200F2
#define HIDD_PROPPAGE_STW_SELECTTEMPLATE        0x200F3
#define HIDD_PROPPAGE_STW_CHOOSETRACKFONTS      0x200F4
#define HIDD_PROPPAGE_STW_CHOOSEBKCOLORS        0x200F5
#define HIDD_PROPPAGE_STW_COVER                 0x200F6
#define HIDD_PROPPAGE_STW_INLAY                 0x200F7
#define HIDD_PROPPAGE_STW_LABEL                 0x200F8
#define HIDD_PROPPAGE_STW_TRACKS                0x200F9
#define HIDD_PROPPAGE_CW_ARRANGETITLES          0x200FA
#define HIDD_PROPPAGE_CW_BACKGROUND             0x200FB
#define HIDD_PROPPAGE_CW_SELECTSTYLE            0x200FC
#define HIDD_PROPPAGE_STW_BOOKLET               0x200FD
#define HIDD_DIALOG_STYLEMEASURES               0x20108
#define HIDD_DIALOG_STYLETRACKS                 0x20109
#define HIDD_DIALOG_STYLETRACKGROUPINGS         0x2010B
 
// Frame Controls (IDW_*) 
// This is a part of the Microsoft Foundation Classes C++ library.
// Copyright (C) Microsoft Corporation
// All rights reserved.
//
// This source code is only intended as a supplement to the
// Microsoft Foundation Classes Reference and related
// electronic documentation provided with the library.
// See these sources for detailed information regarding the
// Microsoft Foundation Classes product.

// Non-Client HitTest help IDs
#define HID_HT_NOWHERE                          0x40000
#define HID_HT_CAPTION                          0x40002
#define HID_HT_SIZE                             0x40004
#define HID_HT_HSCROLL                          0x40006
#define HID_HT_VSCROLL                          0x40007
#define HID_HT_MINBUTTON                        0x40008
#define HID_HT_MAXBUTTON                        0x40009
#define HID_HT_SIZE                             0x4000A // alias: ID_HT_LEFT
#define HID_HT_SIZE                             0x4000B // alias: ID_HT_RIGHT
#define HID_HT_SIZE                             0x4000C // alias: ID_HT_TOP
#define HID_HT_SIZE                             0x4000D // alias: ID_HT_TOPLEFT
#define HID_HT_SIZE                             0x4000E // alias: ID_HT_TOPRIGHT
#define HID_HT_SIZE                             0x4000F // alias: ID_HT_BOTTOM
#define HID_HT_SIZE                             0x40010 // alias: ID_HT_BOTTOMLEFT
#define HID_HT_SIZE                             0x40011 // alias: ID_HT_BOTTOMRIGHT
#define HID_HT_SIZE                             0x40012 // alias: ID_HT_BORDER
#define HID_HT_OBJECT							0x40013
#define HID_HT_CLOSE							0x40014
#define HID_HT_HELP								0x40015

// WM_SYSCOMMAND help IDs
#define HID_SC_SIZE                             0x1EF00
#define HID_SC_MOVE                             0x1EF01
#define HID_SC_MINIMIZE                         0x1EF02
#define HID_SC_MAXIMIZE                         0x1EF03
#define HID_SC_NEXTWINDOW                       0x1EF04
#define HID_SC_PREVWINDOW                       0x1EF05
#define HID_SC_CLOSE                            0x1EF06
#define HID_SC_RESTORE                          0x1EF12
#define HID_SC_TASKLIST                         0x1EF13

// File MRU and aliases
#define HID_FILE_MRU_FILE1                      0x1E110
#define HID_FILE_MRU_FILE1                      0x1E111 // aliases: MRU_2 - MRU_16
#define HID_FILE_MRU_FILE1                      0x1E112
#define HID_FILE_MRU_FILE1                      0x1E113
#define HID_FILE_MRU_FILE1                      0x1E114
#define HID_FILE_MRU_FILE1                      0x1E115
#define HID_FILE_MRU_FILE1                      0x1E116
#define HID_FILE_MRU_FILE1                      0x1E117
#define HID_FILE_MRU_FILE1                      0x1E118
#define HID_FILE_MRU_FILE1                      0x1E119
#define HID_FILE_MRU_FILE1                      0x1E11A
#define HID_FILE_MRU_FILE1                      0x1E11B
#define HID_FILE_MRU_FILE1                      0x1E11C
#define HID_FILE_MRU_FILE1                      0x1E11D
#define HID_FILE_MRU_FILE1                      0x1E11E
#define HID_FILE_MRU_FILE1                      0x1E11F

// Window menu list
#define HID_WINDOW_ALL                          0x1EF1F

// OLE menu and aliases
#define HID_OLE_VERB_1                          0x1E210
#define HID_OLE_VERB_1                          0x1E211 // aliases: VERB_2 -> VERB_16
#define HID_OLE_VERB_1                          0x1E212
#define HID_OLE_VERB_1                          0x1E213
#define HID_OLE_VERB_1                          0x1E214
#define HID_OLE_VERB_1                          0x1E215
#define HID_OLE_VERB_1                          0x1E216
#define HID_OLE_VERB_1                          0x1E217
#define HID_OLE_VERB_1                          0x1E218
#define HID_OLE_VERB_1                          0x1E219
#define HID_OLE_VERB_1                          0x1E21A
#define HID_OLE_VERB_1                          0x1E21B
#define HID_OLE_VERB_1                          0x1E21C
#define HID_OLE_VERB_1                          0x1E21D
#define HID_OLE_VERB_1                          0x1E21E
#define HID_OLE_VERB_1                          0x1E21F

// Commands (HID_*) 
#define HID_FILE_NEW                            0x1E100
#define HID_FILE_OPEN                           0x1E101
#define HID_FILE_CLOSE                          0x1E102
#define HID_FILE_SAVE                           0x1E103
#define HID_FILE_SAVE_AS                        0x1E104
#define HID_FILE_PAGE_SETUP                     0x1E105
#define HID_FILE_PRINT_SETUP                    0x1E106
#define HID_FILE_PRINT                          0x1E107
#define HID_FILE_PRINT_DIRECT                   0x1E108
#define HID_FILE_PRINT_PREVIEW                  0x1E109
#define HID_FILE_UPDATE                         0x1E10A
#define HID_FILE_SAVE_COPY_AS                   0x1E10B
#define HID_FILE_SEND_MAIL                      0x1E10C
#define HID_EDIT_CLEAR                          0x1E120
#define HID_EDIT_CLEAR_ALL                      0x1E121
#define HID_EDIT_COPY                           0x1E122
#define HID_EDIT_CUT                            0x1E123
#define HID_EDIT_FIND                           0x1E124
#define HID_EDIT_PASTE                          0x1E125
#define HID_EDIT_PASTE_LINK                     0x1E126
#define HID_EDIT_PASTE_SPECIAL                  0x1E127
#define HID_EDIT_REPEAT                         0x1E128
#define HID_EDIT_REPLACE                        0x1E129
#define HID_EDIT_SELECT_ALL                     0x1E12A
#define HID_EDIT_UNDO                           0x1E12B
#define HID_EDIT_REDO                           0x1E12C
#define HID_WINDOW_NEW                          0x1E130
#define HID_WINDOW_ARRANGE                      0x1E131
#define HID_WINDOW_CASCADE                      0x1E132
#define HID_WINDOW_TILE_HORZ                    0x1E133
#define HID_WINDOW_TILE_VERT                    0x1E134
#define HID_WINDOW_SPLIT                        0x1E135
#define HID_APP_ABOUT                           0x1E140
#define HID_APP_EXIT                            0x1E141
#define HID_HELP_INDEX                          0x1E142
#define HID_HELP_FINDER                         0x1E143
#define HID_HELP_USING                          0x1E144
#define HID_CONTEXT_HELP                        0x1E145
#define HID_NEXT_PANE                           0x1E150
#define HID_PREV_PANE                           0x1E151
#define HID_FORMAT_FONT                         0x1E160
#define HID_OLE_INSERT_NEW                      0x1E200
#define HID_OLE_EDIT_LINKS                      0x1E201
#define HID_OLE_EDIT_CONVERT                    0x1E202
#define HID_OLE_EDIT_CHANGE_ICON                0x1E203
#define HID_OLE_EDIT_PROPERTIES                 0x1E204
#define HID_VIEW_TOOLBAR                        0x1E800
#define HID_VIEW_STATUS_BAR                     0x1E801
#define HID_RECORD_FIRST                        0x1E900
#define HID_RECORD_LAST                         0x1E901
#define HID_RECORD_NEXT                         0x1E902
#define HID_RECORD_PREV                         0x1E903
#define HID_WIZBACK                             0x13023
#define HID_WIZNEXT                             0x13024
#define HID_WIZFINISH                           0x13025

// Dialogs (AFX_HIDD_*)
#define AFX_HIDD_FILEOPEN                       0x27004
#define AFX_HIDD_FILESAVE                       0x27005
#define AFX_HIDD_FONT                           0x27006
#define AFX_HIDD_COLOR                          0x27007
#define AFX_HIDD_PRINT                          0x27008
#define AFX_HIDD_PRINTSETUP                     0x27009
#define AFX_HIDD_FIND                           0x2700A
#define AFX_HIDD_REPLACE                        0x2700B
#define AFX_HIDD_NEWTYPEDLG                     0x27801
#define AFX_HIDD_PRINTDLG                       0x27802
#define AFX_HIDD_PREVIEW_TOOLBAR                0x27803
#define AFX_HIDD_PREVIEW_SHORTTOOLBAR           0x2780B
#define AFX_HIDD_INSERTOBJECT                   0x27804
#define AFX_HIDD_CHANGEICON                     0x27805
#define AFX_HIDD_CONVERT                        0x27806
#define AFX_HIDD_PASTESPECIAL                   0x27807
#define AFX_HIDD_EDITLINKS                      0x27808
#define AFX_HIDD_FILEBROWSE                     0x27809
#define AFX_HIDD_BUSY                           0x2780A
#define AFX_HIDD_OBJECTPROPERTIES               0x2780C
#define AFX_HIDD_CHANGESOURCE                   0x2780D

// Prompts/Errors (AFX_HIDP_*)
#define AFX_HIDP_NO_ERROR_AVAILABLE             0x3F020
#define AFX_HIDP_INVALID_FILENAME               0x3F100
#define AFX_HIDP_FAILED_TO_OPEN_DOC             0x3F101
#define AFX_HIDP_FAILED_TO_SAVE_DOC             0x3F102
#define AFX_HIDP_ASK_TO_SAVE                    0x3F103
#define AFX_HIDP_FAILED_TO_CREATE_DOC           0x3F104
#define AFX_HIDP_FILE_TOO_LARGE                 0x3F105
#define AFX_HIDP_FAILED_TO_START_PRINT          0x3F106
#define AFX_HIDP_FAILED_TO_LAUNCH_HELP          0x3F107
#define AFX_HIDP_INTERNAL_FAILURE               0x3F108
#define AFX_HIDP_COMMAND_FAILURE                0x3F109
#define AFX_HIDP_FAILED_MEMORY_ALLOC            0x3F10A
#define AFX_HIDP_UNREG_DONE                     0x3F10B
#define AFX_HIDP_UNREG_FAILURE                  0x3F10C
#define AFX_HIDP_DLL_LOAD_FAILED                0x3F10D
#define AFX_HIDP_DLL_BAD_VERSION                0x3F10E
#define AFX_HIDP_PARSE_INT                      0x3F110
#define AFX_HIDP_PARSE_REAL                     0x3F111
#define AFX_HIDP_PARSE_INT_RANGE                0x3F112
#define AFX_HIDP_PARSE_REAL_RANGE               0x3F113
#define AFX_HIDP_PARSE_STRING_SIZE              0x3F114
#define AFX_HIDP_PARSE_RADIO_BUTTON             0x3F115
#define AFX_HIDP_PARSE_BYTE                     0x3F116
#define AFX_HIDP_PARSE_UINT                     0x3F117
#define AFX_HIDP_PARSE_DATETIME                 0x3F118
#define AFX_HIDP_PARSE_CURRENCY                 0x3F119
#define AFX_HIDP_FAILED_INVALID_FORMAT          0x3F120
#define AFX_HIDP_FAILED_INVALID_PATH            0x3F121
#define AFX_HIDP_FAILED_DISK_FULL               0x3F122
#define AFX_HIDP_FAILED_ACCESS_READ             0x3F123
#define AFX_HIDP_FAILED_ACCESS_WRITE            0x3F124
#define AFX_HIDP_FAILED_IO_ERROR_READ           0x3F125
#define AFX_HIDP_FAILED_IO_ERROR_WRITE          0x3F126
#define AFX_HIDP_STATIC_OBJECT                  0x3F180
#define AFX_HIDP_FAILED_TO_CONNECT              0x3F181
#define AFX_HIDP_SERVER_BUSY                    0x3F182
#define AFX_HIDP_BAD_VERB                       0x3F183
#define AFX_HIDP_FAILED_TO_NOTIFY               0x3F185
#define AFX_HIDP_FAILED_TO_LAUNCH               0x3F186
#define AFX_HIDP_ASK_TO_UPDATE                  0x3F187
#define AFX_HIDP_FAILED_TO_UPDATE               0x3F188
#define AFX_HIDP_FAILED_TO_REGISTER             0x3F189
#define AFX_HIDP_FAILED_TO_AUTO_REGISTER        0x3F18A
#define AFX_HIDP_FAILED_TO_CONVERT              0x3F18B
#define AFX_HIDP_GET_NOT_SUPPORTED              0x3F18C
#define AFX_HIDP_SET_NOT_SUPPORTED              0x3F18D
#define AFX_HIDP_ASK_TO_DISCARD                 0x3F18E
#define AFX_HIDP_FAILED_TO_CREATE               0x3F18F
#define AFX_HIDP_FAILED_MAPI_LOAD               0x3F190
#define AFX_HIDP_INVALID_MAPI_DLL               0x3F191
#define AFX_HIDP_FAILED_MAPI_SEND               0x3F192
#define AFX_HIDP_FILE_NONE                      0x3F1A0
#define AFX_HIDP_FILE_GENERIC                   0x3F1A1
#define AFX_HIDP_FILE_NOT_FOUND                 0x3F1A2
#define AFX_HIDP_FILE_BAD_PATH                  0x3F1A3
#define AFX_HIDP_FILE_TOO_MANY_OPEN             0x3F1A4
#define AFX_HIDP_FILE_ACCESS_DENIED             0x3F1A5
#define AFX_HIDP_FILE_INVALID_FILE              0x3F1A6
#define AFX_HIDP_FILE_REMOVE_CURRENT            0x3F1A7
#define AFX_HIDP_FILE_DIR_FULL                  0x3F1A8
#define AFX_HIDP_FILE_BAD_SEEK                  0x3F1A9
#define AFX_HIDP_FILE_HARD_IO                   0x3F1AA
#define AFX_HIDP_FILE_SHARING                   0x3F1AB
#define AFX_HIDP_FILE_LOCKING                   0x3F1AC
#define AFX_HIDP_FILE_DISKFULL                  0x3F1AD
#define AFX_HIDP_FILE_EOF                       0x3F1AE
#define AFX_HIDP_ARCH_NONE                      0x3F1B0
#define AFX_HIDP_ARCH_GENERIC                   0x3F1B1
#define AFX_HIDP_ARCH_READONLY                  0x3F1B2
#define AFX_HIDP_ARCH_ENDOFFILE                 0x3F1B3
#define AFX_HIDP_ARCH_WRITEONLY                 0x3F1B4
#define AFX_HIDP_ARCH_BADINDEX                  0x3F1B5
#define AFX_HIDP_ARCH_BADCLASS                  0x3F1B6
#define AFX_HIDP_ARCH_BADSCHEMA                 0x3F1B7
#define AFX_HIDP_SQL_CONNECT_FAIL               0x3F281
#define AFX_HIDP_SQL_RECORDSET_FORWARD_ONLY     0x3F282
#define AFX_HIDP_SQL_EMPTY_COLUMN_LIST          0x3F283
#define AFX_HIDP_SQL_FIELD_SCHEMA_MISMATCH      0x3F284
#define AFX_HIDP_SQL_ILLEGAL_MODE               0x3F285
#define AFX_HIDP_SQL_MULTIPLE_ROWS_AFFECTED     0x3F286
#define AFX_HIDP_SQL_NO_CURRENT_RECORD          0x3F287
#define AFX_HIDP_SQL_NO_ROWS_AFFECTED           0x3F288
#define AFX_HIDP_SQL_RECORDSET_READONLY         0x3F289
#define AFX_HIDP_SQL_SQL_NO_TOTAL               0x3F28A
#define AFX_HIDP_SQL_ODBC_LOAD_FAILED           0x3F28B
#define AFX_HIDP_SQL_DYNASET_NOT_SUPPORTED      0x3F28C
#define AFX_HIDP_SQL_SNAPSHOT_NOT_SUPPORTED     0x3F28D
#define AFX_HIDP_SQL_API_CONFORMANCE            0x3F28E
#define AFX_HIDP_SQL_SQL_CONFORMANCE            0x3F28F
#define AFX_HIDP_SQL_NO_DATA_FOUND              0x3F290
#define AFX_HIDP_SQL_ROW_UPDATE_NOT_SUPPORTED   0x3F291
#define AFX_HIDP_SQL_ODBC_V2_REQUIRED           0x3F292
#define AFX_HIDP_SQL_NO_POSITIONED_UPDATES      0x3F293
#define AFX_HIDP_SQL_LOCK_MODE_NOT_SUPPORTED    0x3F294
#define AFX_HIDP_SQL_DATA_TRUNCATED             0x3F295
#define AFX_HIDP_SQL_ROW_FETCH                  0x3F296
#define AFX_HIDP_SQL_INCORRECT_ODBC             0x3F297
#define AFX_HIDP_SQL_UPDATE_DELETE_FAILED       0x3F298
#define AFX_HIDP_SQL_DYNAMIC_CURSOR_NOT_SUPPORTED	0x3F299
#define AFX_HIDP_SQL_FIELD_NOT_FOUND            0x3F29A
#define AFX_HIDP_SQL_BOOKMARKS_NOT_SUPPORTED    0x3F29B
#define AFX_HIDP_SQL_BOOKMARKS_NOT_ENABLED      0x3F29C
#define AFX_HIDP_DAO_ENGINE_INITIALIZATION      0x3F2B0
#define AFX_HIDP_DAO_DFX_BIND                   0x3F2B1
#define AFX_HIDP_DAO_OBJECT_NOT_OPEN            0x3F2B2
#define AFX_HIDP_DAO_ROWTOOSHORT                0x3F2B3
#define AFX_HIDP_DAO_BADBINDINFO                0x3F2B4
#define AFX_HIDP_DAO_COLUMNUNAVAILABLE          0x3F2B5

// Frame Controls (AFX_HIDW_*)
#define AFX_HIDW_TOOLBAR                        0x5E800
#define AFX_HIDW_STATUS_BAR                     0x5E801
#define AFX_HIDW_PREVIEW_BAR                    0x5E802
#define AFX_HIDW_RESIZE_BAR                     0x5E803
#define AFX_HIDW_DOCKBAR_TOP                    0x5E81B
#define AFX_HIDW_DOCKBAR_LEFT                   0x5E81C
#define AFX_HIDW_DOCKBAR_RIGHT                  0x5E81D
#define AFX_HIDW_DOCKBAR_BOTTOM                 0x5E81E
#define AFX_HIDW_DOCKBAR_FLOAT                  0x5E81F

/////////////////////////////////////////////////////////////////////////////
