//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CdCoverCreator2.rc
//
#define ID__REMOVE_REMARKS              0
#define IDR_MANIFEST                    1
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDC_TREE_BROWSER                101
#define IDS_PROPSHT_CAPTION             102
#define IDD_DIALOG_COVERSLIST           102
#define IDC_LIST_BROWSER                102
#define IDD_PROPPAGE1                   103
#define IDS_DONE                        103
#define IDC_EDIT_BROWSER                103
#define IDD_DIALOGBAR_MEDIUM            103
#define IDD_PROPPAGE2                   104
#define IDS_OPENBKIMGFILE_FILENAME      104
#define IDC_ANIMATION_BROWSER           104
#define IDS_OPENBKIMGFILE_FILTER        105
#define IDS_INVALIDPICTURE              106
#define IDS_NOAUDIOCD                   107
#define IDS_PROPSHT_CAPTION1            108
#define IDD_PROPPAGE11                  109
#define IDS_TEMPLATE_ALREADYEXISTS      109
#define IDD_PROPPAGE21                  110
#define IDS_SAVETEMPLATE                110
#define IDD_PROPPAGE31                  111
#define IDS_NEWTEMPLATENAMEEMPTY        111
#define IDR_POPUP_LABELITVIEW           112
#define IDS_NOCDDRIVE                   112
#define IDS_INTERNETERROR               113
#define IDS_PREVIEW                     114
#define IDS_NODATAAVAILABLE             115
#define IDS_QUERYEMPTY                  116
#define IDS_INTERNETERROR_UPDATE        117
#define IDS_INTERNETERROR_IMAGES        118
#define IDS_NONEWVERSION                119
#define IDS_ERROR_PRINTTEST             120
#define IDS_PROPSHT_CAPTION2            121
#define IDD_PROPPAGE13                  122
#define IDS_OPENBKALPHAIMGFILE_FILENAME 122
#define IDD_PROPPAGE_PS_HOSTS           122
#define IDD_PROPPAGE23                  123
#define IDS_OPENBKALPHAIMGFILE_FILTER   123
#define IDD_PROPPAGE_PS_VERSIONCHECKING 123
#define IDD_PROPPAGE32                  124
#define IDS_OPENM3U_FILENAME            124
#define IDD_PROPPAGE_PS_PRINTERSETTINGS 124
#define IDS_OPENM3U_FILTER              125
#define IDS_CONFIRM_DELETETEMPLATE      126
#define IDR_HTML_DLGABOUT               127
#define IDR_MAINFRAME                   128
#define IDR_CdCoverCreatorTYPE          129
#define IDR_LABELSTYPE                  129
#define IDD_DIALOG_COVERSSEARCH         129
#define IDI_ICON_CC                     130
#define IDC_BUTTON_SEARCH               130
#define IDR_MENU_OPEN                   130
#define IDS_ERROR_ACCESSING_URL         130
#define IDI_ICON_TL                     131
#define IDC_SPLITTER                    131
#define ID__OPENFILE                    131
#define ID_LIGHTSCRIBE_PANE             131
#define IDI_ICON_TC                     132
#define IDC_TREE_IMAGES                 132
#define ID__BEMERKUNGENL                132
#define ID_LIGHTSCRIBE_PROGRESS         132
#define IDI_ICON_TR                     133
#define IDC_LIST_BKTEXTURES             133
#define ID__REMOVEREMARKS               133
#define ID_LIGHTSCRIBE_TIME_LEFT        133
#define IDI_ICON_CL                     134
#define IDC_LIST_BKALPHAS               134
#define IDR_RAINBOW                     134
#define IDI_ICON_CR                     135
#define IDC_LIST_WEB                    135
#define IDD_DIALOG_SELECTLABELS         135
#define IDI_ICON_BL                     136
#define IDC_BUTTON_NEWLINK              136
#define IDI_ICON_BR                     137
#define IDC_BUTTON_DELLINK              137
#define IDC_BUTTON_WINDOWSLIST          138
#define IDD_PAGESETUPDLG_PF             138
#define IDI_ICON_BC                     139
#define IDC_BUTTON_M3U                  139
#define IDR_MENU_FLOATINGIMAGE          139
#define IDD_PROPPAGE3                   140
#define IDC_LIST_SEARCH                 140
#define ID__SELECTTRANSPARENTCOLOR      140
#define IDI_ICON_SEP                    141
#define IDC_EDIT_SEARCHARTIST           141
#define ID__RAISE                       141
#define IDI_ICON_TRACK                  142
#define IDC_EDIT_SEARCHALBUM            142
#define ID__LOWER                       142
#define IDR_MENU_TRACK                  143
#define IDC_EDIT_SEARCHSONG             143
#define ID__BRINGTOFRONT                143
#define IDR_MENU_SEP                    144
#define IDC_FINISH                      144
#define ID__SENDTOBACK                  144
#define IDC_CURSOR_HAND                 145
#define IDC_VIEWRICHEDIT                145
#define ID__DELETE                      145
#define IDC_VIEWTRACKEDIT               146
#define IDR_MENU_FLOATINGTEXT           146
#define ID_SEARCH                       147
#define ID__RAISE147                    147
#define IDI_ICON_UP                     148
#define ID_ASSIGNTO                     148
#define ID__LOWER148                    148
#define IDI_ICON_DOWN                   149
#define ID__BRINGTOFRONT149             149
#define IDD_PROPPAGE01                  150
#define ID__SENDTOBACK150               150
#define IDI_ICON_FONT                   151
#define ID__DELETE151                   151
#define IDI_ICON_COLORS                 152
#define ID__STRETCHTOFULLCOVERSIZE      152
#define IDI_ICON_BROWSE                 153
#define ID__ALIGN                       153
#define ID_ALIGN_TOPLEFT                154
#define IDI_ICON_STYLE                  155
#define ID_ALIGN_TOPMIDDLE              155
#define IDD_DIALOG_PICKTITLE            156
#define ID_ALIGN_TOPRIGHT               156
#define ID_ALIGN_MIDDLELEFT             157
#define ID_ALIGN_MIDDLEMIDDLE           158
#define ID_ALIGN_MIDDLERIGHT            159
#define IDC_PROGRESS_BROWSER            160
#define ID_ALIGN_BOTTOMLEFT             160
#define IDS_BUTTON_SEARCH               161
#define ID_ALIGN_BOTTOMMIDDLE           161
#define IDS_BROWSER_LIST                162
#define ID_ALIGN_BOTTOMRIGHT            162
#define IDT_GREENDAY                    163
#define IDS_BROWSER_SEARCH              163
#define IDD_PROPPAGE_CW_CREATEDATACD    163
#define IDS_BROWSER_IMAGES              164
#define ID_NEW_DATACD                   164
#define IDR_AVIFIND                     165
#define IDS_BROWSER_BKTEXTURES          165
#define ID_NEU_DATEN                    165
#define IDS_BROWSER_WEB                 166
#define ID_NEW_DATACD166                166
#define IDD_DIALOG_PRINTTEMPLATE        167
#define ID_NEU_DATEN167                 167
#define IDS_BROWSER_APPLY               168
#define ID_TOOLS_ADDTEXT168             168
#define IDR_TOOLBAR_GRP                 169
#define ID_TOOLS_ADDIMAGE169            169
#define IDS_STATIC_ARTISTSEARCH         170
#define ID_TOOLS_SELECTBACKGROUNDIMAGE  170
#define IDD_DIALOG_MATCHMERGE           171
#define IDS_STATIC_ALBUMSEARCH          171
#define ID_TOOLS_SCANBACKGROUNDIMAGE    171
#define IDD_PROPPAGE20                  172
#define IDS_STATIC_SONGSEARCH           172
#define IDD_PROPPAGE22                  173
#define IDB_BITMAP_AITEC                173
#define IDD_PROPPAGE10                  174
#define IDD_DIALOG_ABOUT_PF             174
#define IDB_BITMAP_PEROUTKA             175
#define ID_HELP_CDCOVERCREATORONTHEWEB  176
#define ID_HILFE_CDCOVERCREATORONTHEWEB 177
#define IDD_DIALOG_PICKDRIVE            178
#define ID_HELP_CDCOVERCREATORONTHEWEB178 178
#define IDD_PAGESETUPDLG                179
#define ID_HILFE_CDCOVERCREATORONTHEWEB179 179
#define IDS_WEBADDRESS                  180
#define IDS_LABELTITLEPOS_ABOVE         181
#define IDD_DIALOG_STYLESPINES          181
#define IDS_LABELTITLEPOS_BELOW         182
#define IDS_LEFT                        183
#define IDR_MENU1                       183
#define IDR_MENU_CWSPECIALFUNCTIONS     183
#define IDS_RIGHT                       184
#define ID__MATCHMERGE                  184
#define IDD_PROPPAGE12                  185
#define IDS_TOP                         185
#define ID__COPYTRACKLISTINGTOCLIPBOARD 185
#define IDC_CURSOR_PICKER               186
#define IDS_BOTTOM                      186
#define ID__EXPORTTRACKLISTINGASHTML    186
#define IDI_SETTRANSPARENT              187
#define IDS_HORZMARGIN                  187
#define IDI_REMOVETRANSPARENT           188
#define IDS_VERTMARGIN                  188
#define IDS_MEASURES                    189
#define IDR_JPEG_SPLASHSCREEN           189
#define IDR_JPEG_SPLASHSCREEN_PF        190
#define IDD_DIALOG_ABOUT                191
#define IDR_JPEG_ABOUTBK                192
#define IDR_JPEG_PAYPAL                 193
#define ID__REMOVEREMARKS194            194
#define IDI_ICON_SCAN                   195
#define ID__BEMERKUNGENENTFERNEN        195
#define IDD_DIALOG_IMAGEPROPERTIES      196
#define ID__ADJUSTCOLORS                197
#define IDD_DIALOG_PROGSETTINGS         198
#define ID_                             198
#define IDD_DIALOG_UPDATE               199
#define ID_199                          199
#define IDS_CDDB_NOMATCH                200
#define ID_200                          200
#define IDS_CDDB_DBENTRYCORRUPT         201
#define IDD_DIALOG_PRINTTESTCANCEL      201
#define ID_X                            201
#define IDS_CDDB_NOHANDSHAKE            202
#define IDR_TOOLBAR2                    202
#define IDR_TOOLBAR_WINDOW              202
#define IDS_CDDB_UNDEFINEDERROR         203
#define IDS_DOWNLOADING_LIST            204
#define ID_VIEW_TEXTTOOLBAR             204
#define IDS_SEARCHING                   205
#define IDS_DOWNLOADING_IMAGE           206
#define IDR_TOOLBAR_NEW                 206
#define IDS_COL_DEFAULT                 207
#define ID_FENSTER_N                    207
#define IDD_DIALOG_STYLE                208
#define IDS_COL_CUSTOM                  208
#define ID_FENSTER_VORHERIGESFENSTER    208
#define IDD_LEFTPANEL                   209
#define IDS_LEFTPANELCAPTION            209
#define ID__BACKGROUNDIMAGE             209
#define IDS_SEARCHWEBCDCOVERS           210
#define ID_BACKGROUNDIMAGE_TILE         210
#define IDS_DOWNLOADSTATUS_KB           211
#define ID_BACKGROUNDIMAGE_EDIT         211
#define IDS_DOWNLOADSTATUS_PERCENT      212
#define ID_BACKGROUNDIMAGE_RELOAD       212
#define IDS_DOWNLOADSTATUS_KBS          213
#define IDD_DIALOG1                     213
#define IDD_PROPPAGE_PS_IMAGEEDITING    213
#define IDR_TOOLBAR_BROWSE              214
#define ID__EDITIMAGE                   214
#define ID__RELOADIMAGE                 215
#define IDD_DIALOG_SETIMAGEEDITOR       216
#define IDI_ICON_FOLDER                 217
#define IDB_BITMAP1                     217
#define IDB_BITMAP_AUDIOCD              217
#define IDI_ICON_WEBCOVER               218
#define IDR_MENU_GRADIENT               218
#define IDR_HTML_EMPTY                  219
#define ID_GRADIENT_LINEAR              219
#define IDS_LYRICSBROWSER_TITLE         220
#define ID_GRADIENT_RECTANGULAR         220
#define IDI_ICON_NEWLINK                221
#define ID_GRADIENT_DIAMOND             221
#define IDI_ICON_DELLINK                222
#define ID_GRADIENT_RADIAL              222
#define IDD_DIALOG_ROLLUP               223
#define ID_GRADIENT_TRIANGULAR          223
#define IDD_DIALOG_STYLEBKIMG           224
#define ID_GRADIENT_RADIALTOP           224
#define IDD_DIALOG_STYLEALPHA           225
#define ID_GRADIENT_WHEEL               225
#define IDR_MENU_FLOATINGBARCODE        225
#define IDD_DIALOG_BARCODEPROPS         226
#define IDR_TOOLBAR_LYRICSBROWSER       227
#define IDD_DIALOG_LIGHTSCRIBE          228
#define IDI_ICON_M3U                    229
#define IDR_COVERBROWSER                230
#define IDR_LYRICSBROWSER               231
#define IDI_ICON_WINDOWSLIST            232
#define IDI_ICON_LYRICS                 233
#define IDI_ICON_LYRICS_OK              234
#define IDI_ICON_LYRICS_NOTFOUND        235
#define IDR_TOOLBAR_RTFFORMAT           236
#define IDD_DIALOG_STYLEFONTS           239
#define IDD_FILEOPENPREVIEW             240
#define IDS_DLGSTYLE_GRADIENT           240
#define IDS_DLGSTYLE_BKIMGS             241
#define IDS_DLGSTYLE_ALPHA              242
#define IDD_PROPPAGE_STW_CHOOSETITLEFONTS 242
#define IDS_DLGSTYLE_FONTS              243
#define IDD_PROPPAGE_STW_SELECTTEMPLATE 243
#define IDD_PROPPAGE_STW_CHOOSETRACKFONTS 244
#define IDS_DLGSTYLE_TITLES             244
#define IDD_PROPPAGE_STW_CHOOSEBKCOLORS 245
#define IDS_DLGSTYLE_TRACKS             245
#define IDD_PROPPAGE_STW_COVER          246
#define IDS_DLGSTYLE_TRACKGROUPINGS     246
#define IDD_PROPPAGE_STW_INLAY          247
#define IDS_DLGSTYLE_SPINES             247
#define IDD_PROPPAGE_STW_LABEL          248
#define IDD_PROPPAGE_STW_TRACKS         249
#define IDD_PROPPAGE_CW_ARRANGETITLES   250
#define IDD_PROPPAGE_CW_BACKGROUND      251
#define IDD_PROPPAGE_CW_SELECTSTYLE     252
#define IDD_PROPPAGE_STW_BOOKLET        253
#define IDR_TOOLBAR1                    256
#define IDR_MENU_RTF_BORDER             258
#define IDR_MENU_RTF_BULLETS            259
#define IDR_TOOLBAR_RTF_BORDER          260
#define IDR_TOOLBAR_RTF_BULLETS         262
#define IDD_DIALOG_STYLEMEASURES        264
#define IDD_DIALOG_STYLETRACKS          265
#define IDD_DIALOG_STYLETRACKGROUPINGS  267
#define IDB_BITMAP_AMAZON               268
#define IDI_ICON_PRINTPOWER             271
#define IDI_ICON_FUNPRINT               272
#define IDS_COVERBKIMAGE                300
#define IDS_LABELBKIMAGE                301
#define IDS_INLAYBKIMAGE                302
#define IDS_BACKBKIMAGE                 303
#define IDS_PRINTTEST_1                 400
#define IDS_PRINTTEST_2                 401
#define IDS_PRINTTEST_3                 402
#define IDS_PRINTTEST_4                 403
#define IDS_PRINTTEST_CHECK             404
#define IDS_PRINTTEST_CHECK_IFNOT       405
#define IDS_PRINTTEST_CHECKLAST         406
#define IDS_PRINTTEST_CAPTION           408
#define IDS_TEXT                        420
#define IDS_BACKGROUND                  421
#define IDS_FINISH                      430
#define IDS_SEARCH                      431
#define IDS_ASSIGNTO                    432
#define IDS_TT_BROWSE                   500
#define IDS_TT_SCAN                     501
#define IDS_TT_LISTWEB                  502
#define IDS_TT_SEARCHWEB                503
#define IDS_TT_TRANSPARENT              504
#define IDS_TT_REMOVETRANSPARENT        505
#define IDS_TT_STYLEED                  506
#define IDS_TT_FONT                     507
#define IDS_TT_COLOR                    508
#define IDS_TT_DIRECTION                509
#define IDS_TT_MOVEUP                   510
#define IDS_TT_MOVEDOWN                 511
#define IDS_DOWNLOADCOVERNOTE           600
#define IDS_AMAZON                      601
#define IDS_AMAZON_ASSOC                602
#define IDS_ERROR_HTTPREQUEST           603
#define IDS_TRANSPARENCYNOTSUPPORTED    604
#define ID_WINDOW_NEXTWINDOW            701
#define ID_WINDOW_PREVIOUSWINDOW        702
#define IDC_EDIT_BKIMGFILENAME          1000
#define IDC_LIST                        1000
#define IDC_EDIT_FILE                   1000
#define IDC_LABELSELECTOR               1000
#define IDC_BUTTON_ADDGRP               1001
#define IDC_BUTTON_TITLEFONT            1001
#define IDC_BUTTON_TRACK_UP             1001
#define IDC_BUTTON_STYLE                1001
#define IDC_BUTTON_TITLEFONT_INLAYTITLEFONT 1001
#define IDC_EDIT_KEYWORDS               1001
#define IDC_EDIT_LETTER                 1001
#define IDC_IMAGE                       1001
#define IDC_BUTTON_SIDEBARFONT          1002
#define IDC_BUTTON_TRACK_DOWN           1002
#define IDC_BUTTON_TITLEFONT_INLAYSIDEFONT 1002
#define IDC_EDIT_MAXNESTING             1002
#define IDC_BUTTON_REMOVEGRP            1003
#define IDC_SPIN_MAXNESTING             1003
#define IDC_BROWSEBKIMG                 1004
#define IDC_BUTTON_TRACKGROUPINGREMARKS_FONT 1004
#define IDC_BUTTON_BROWSE               1004
#define IDC_PREVIEW                     1005
#define IDC_BUTTON_TRACKLENGTH_FONT     1005
#define IDC_BUTTON_TITLEFONT_LABELFONT  1005
#define IDC_STATIC_STATUS               1005
#define IDC_EDIT_COLUMNSCOUNT           1005
#define IDC_BUTTON_PREVIEW              1006
#define IDC_BUTTON_TRACKTITLE_FONT      1006
#define IDC_STATIC_IMAGE                1006
#define IDC_SPIN_COLUMNSCOUNT           1006
#define IDC_RADIO1                      1007
#define IDC_BUTTON_TRACKNUM_FONT        1007
#define IDC_BUTTON_TITLEFONT_COVERFONT  1007
#define IDC_CHECK_USESYSTEMICONS        1007
#define IDC_RADIO2                      1008
#define IDC_BUTTON_TRACKREMARKS_FONT    1008
#define IDC_BUTTON_GO                   1008
#define IDC_RADIO3                      1009
#define IDC_BUTTON_TRACKGROUPINGTITLE_FONT 1009
#define IDC_PROGRESS                    1009
#define IDC_RADIO_SPINETEXTDIR_UP       1009
#define IDC_RADIO4                      1010
#define IDC_BUTTON_FONT                 1010
#define IDC_RADIO_SPINETEXTDIR_DOWN     1010
#define IDC_RADIO5                      1011
#define IDC_BUTTON_CDTEXT               1011
#define IDC_RADIO6                      1012
#define IDC_COMBO_MEDIUM                1012
#define IDC_RADIO7                      1013
#define IDC_BUTTON_SPECIALFUNCTIONS     1013
#define IDC_RADIO8                      1014
#define IDC_SLIDER_CONTRAST             1014
#define IDC_RADIO9                      1015
#define IDC_STATIC_CONTRAST             1015
#define IDC_RADIO10                     1016
#define IDC_SLIDER_BRIGHTNESS           1016
#define IDC_RADIO11                     1017
#define IDC_STATIC_BRIGHTNESS           1017
#define IDC_LIST_TRACKS                 1018
#define IDC_BUTTON_LISTCDCOVERS         1018
#define IDC_SLIDER_SATURATION           1018
#define IDC_EDIT_TITLE                  1019
#define IDC_BUTTON_SEARCHCDCOVERS       1019
#define IDC_STATIC_SATURATION           1019
#define IDC_EDIT_TITLE2                 1020
#define IDC_SCAN                        1020
#define IDC_SLIDER_HUE                  1020
#define IDC_COMBO_STYLE                 1021
#define IDC_STATIC_HUE                  1021
#define IDC_PREVIEW_LABEL               1022
#define IDC_SLIDER_GAMMA                1022
#define IDC_STATIC_EMAIL                1023
#define IDC_STATIC_GAMMA                1023
#define IDC_STATIC_TITLEFONT            1024
#define IDC_TITLEFONT_INLAYTITLE        1024
#define IDC_STATIC_INLAY_BKCOLOR        1024
#define IDC_BUTTON_RESET                1024
#define IDC_STATIC_SIDEBARFONT          1025
#define IDC_TITLEFONT_INLAYSIDE         1025
#define IDC_BUTTON_ADJUSTCOLOR          1025
#define IDC_STATIC_TRACKGROUPINGTITLE_FONT 1026
#define IDC_BUTTON1                     1026
#define IDC_BUTTON_EDITIMAGE            1026
#define IDC_STATIC_TRACKNUM_FONT        1027
#define IDC_TITLEFONT_COVER             1027
#define IDC_STATIC_COVER_BKCOLOR        1027
#define IDC_BUTTON_RELOADIMAGE          1027
#define IDC_COMBO_TYPE                  1027
#define IDC_BUTTON_TITLECOLOR           1028
#define IDC_BUTTON_TITLEFONT_INLAYTITLECOLOR 1028
#define IDC_BUTTON_INLAY_BKCOLOR        1028
#define IDC_STATIC_FONT                 1028
#define IDC_COMBO_FONT                  1028
#define IDC_BUTTON_SIDEBARCOLOR         1029
#define IDC_BUTTON_TITLEFONT_INLAYSIDECOLOR 1029
#define IDC_STATIC_BACK_BKCOLOR         1029
#define IDC_BUTTON_FGCOLOR              1029
#define IDC_RADIO_TITLEHALIGN1          1030
#define IDC_RADIO_COVER_TITLEMARGINLEFT 1030
#define IDC_RADIO_LABEL_TITLEVALGNTOP   1030
#define IDC_STATIC_TRACKNUM_FONT2       1030
#define IDC_BUTTON_INLAY_BKCOLOR2       1030
#define IDC_RADIO_TITLEHALIGN2          1031
#define IDC_BUTTON_TRACKGROUPINGREMARKS_COLOR 1031
#define IDC_RADIO_COVER_TITLEMARGINRIGHT 1031
#define IDC_RADIO_LABEL_TITLEVALIGNBOTTOM 1031
#define IDC_CHECK_TRANSPBK              1031
#define IDC_RADIO_TITLEHALIGN3          1032
#define IDC_STATIC_TRACKLENGTH_FONT     1032
#define IDC_RADIO_COVER_TITLEMARGINCENTER 1032
#define IDC_RADIO_LABEL_TITLEVALIGNCENTER 1032
#define IDC_TITLEFONT_LABEL             1032
#define IDC_STATIC_LABEL_BKCOLOR        1032
#define IDC_CHECK_TDANTIPARALLEL        1032
#define IDC_RADIO_SIDEBAR_VALIGN1       1033
#define IDC_STATIC_TRACKTITLE_FONT      1033
#define IDC_RADIO_TITLE_TGMARGINTOP     1033
#define IDC_RADIO_LABEL_TRACKVALIGNTOP  1033
#define IDC_RADIO_PAGENUMALIGNOUTER     1033
#define IDC_RADIO_HALIGN_LEFT           1033
#define IDC_COMBO_QUALITY               1033
#define IDC_RADIO_SIDEBAR_VALIGN2       1034
#define IDC_STATIC_TRACKREMARKS_FONT    1034
#define IDC_RADIO_TITLE_TGMARGINBOTTOM  1034
#define IDC_RADIO_LABEL_TRACKVALIGNBOTTOM 1034
#define IDC_RADIO_PAGENUMALIGNCENTER    1034
#define IDC_RADIO_HALIGN_RIGHT          1034
#define IDC_COMBO_LIGHTSCRIBEDEVICE     1034
#define IDC_RADIO_SIDEBAR_VALIGN3       1035
#define IDC_STATIC_TRACKGROUPINGREMARKS_FONT 1035
#define IDC_RADIO_TITLE_TGVCENTER       1035
#define IDC_RADIO_LABEL_TRACKVALIGNCENTER 1035
#define IDC_RADIO_PAGENUMALIGNINNER     1035
#define IDC_RADIO_HALIGN_CENTER         1035
#define IDC_STATIC_PREVIEW              1035
#define IDC_EDIT_TITLE_HALIGNL          1036
#define IDC_BUTTON_TRACKLENGTH_COLOR    1036
#define IDC_EDIT_LABEL_TITLEVALIGNTOP   1036
#define IDC_BUTTON_TITLEFONT_LABELCOLOR 1036
#define IDC_EDIT_COVER_TITLEHALIGNLEFT  1036
#define IDC_BUTTON_LABEL_BKCOLOR        1036
#define IDC_EDIT_TITLE_HALIGNR          1037
#define IDC_BUTTON_TRACKTITLE_COLOR     1037
#define IDC_EDIT_LABEL_TITLEVALIGNBOTTOM 1037
#define IDC_EDIT_COVER_TITLEHALIGNRIGHT 1037
#define IDC_BUTTON_LABEL_BKCOLOR2       1037
#define IDC_EDIT_TITLE_HEIGHT           1038
#define IDC_BUTTON_TRACKNUM_COLOR       1038
#define IDC_EDIT_COVER_TITLEVALIGNHEIGHT 1038
#define IDC_BUTTON_TITLEFONT_COVERCOLOR 1038
#define IDC_BUTTON_COVER_BKCOLOR        1038
#define IDC_EDIT_TRACKGRP_SPABOVE       1039
#define IDC_BUTTON_TRACKREMARKS_COLOR   1039
#define IDC_EDIT_TITLE_TOP              1039
#define IDC_EDIT_COVER_TITLEVALIGNTOP   1039
#define IDC_BUTTON_BACK_BKCOLOR         1039
#define IDC_EDIT_TRACKGRP_SPBELOW       1040
#define IDC_BUTTON_TRACKGROUPINGTITLE_COLOR 1040
#define IDC_EDIT_SIDE_VALIGNT           1040
#define IDC_EDIT_TITLE_TGMARGINTOP      1040
#define IDC_EDIT_LABEL_TRACKVALIGNTOP   1040
#define IDC_BUTTON_COVER_BKCOLOR2       1040
#define IDC_EDIT_HALIGN_LEFT            1040
#define IDC_CHECK_TRACKGRP_NEWLINE      1041
#define IDC_EDIT_SIDE_VALIGNB           1041
#define IDC_EDIT_TITLE_TGMARGINBOTTOM   1041
#define IDC_EDIT_LABEL_TRACKVALIGNBOTTOM 1041
#define IDC_BUTTON_BACK_BKCOLOR2        1041
#define IDC_BUTTON_COLOR                1041
#define IDC_EDIT_HALIGNRIGHT            1041
#define IDC_CHECK_CREATENEWTEMPLATE     1042
#define IDC_RADIO_TITLE_TGMARGINLEFT    1042
#define IDC_RADIO_VALIGN_TOP            1042
#define IDC_CHECK_TDANTIPARALLEL2       1042
#define IDC_LIST_DISPLAY                1043
#define IDC_RADIO_TITLE_TGMARGINRIGHT   1043
#define IDC_RADIO_VALIGN_BOTTOM         1043
#define IDC_CHECK_TRACKDISPLAY          1044
#define IDC_RADIO_TITLE_TGHCENTERED     1044
#define IDC_RADIO_VALIGN_CENTER         1044
#define IDC_COMBO_TRACKSALIGNMENT       1045
#define IDC_EDIT_TITLE_TGMARGINLEFT     1045
#define IDC_EDIT_VALIGN_TOP             1045
#define IDC_COMBO_TEMPLATE              1046
#define IDC_COMBO_TRACKFORMATTING       1046
#define IDC_EDIT_TITLE_TGMARGINRIGHT    1046
#define IDC_EDIT_VALIGN_BOTTOM          1046
#define IDC_EDIT_TEMPLATENAME           1047
#define IDC_CHECK_DISPLAYTOTALTIME      1048
#define IDC_RADIO_TRACKALIGN            1049
#define IDC_STATIC_TRACKFORMATTINGSAMPLE 1051
#define IDC_EDIT_TRACKH_MARGINL         1052
#define IDC_EDIT_TRACKH_MARGINR         1053
#define IDC_EDIT_TRACKH_INTERITEMSPACING 1054
#define IDC_COMBO_MFR_STYLE             1055
#define IDC_LIST_CDTITLES               1056
#define IDC_LIST_MERGE                  1056
#define IDS_DOWNLOADSTATUS              1056
#define IDC_BUTTON_CDDB                 1057
#define IDC_EDIT1                       1058
#define IDC_EDIT_COVERMARGINLEFT        1058
#define IDC_EDIT_DEGCOVER               1058
#define IDC_EDIT_PRINTCODE              1058
#define IDC_EDIT_BOOKLETMARGLEFT        1058
#define IDC_EDIT_BASEDIR                1058
#define IDC_BUTTON_MATCHMERGE           1059
#define IDC_EDIT_COVERBACKMARGINLEFT    1059
#define IDC_EDIT_DEGBACK                1059
#define IDC_EDIT_BOOKLETMARGTOP         1059
#define IDC_CHECK_DELEXISTING           1060
#define IDC_EDIT_INLAYMARGINLEFT        1060
#define IDC_EDIT_DEGLABEL               1060
#define IDC_EDIT_BOOKLETMARGRIGHT       1060
#define IDC_CHECK_COVER_TITLE_TGSHOW    1061
#define IDC_EDIT_LABELMARGINLEFT        1061
#define IDC_EDIT_DEGINLAY               1061
#define IDC_EDIT_BOOKLETMARGBOTTOM      1061
#define IDC_RADIO_LABEL_TITLEROUND      1062
#define IDC_CHECK_COVER_TITLE_SHOW      1062
#define IDC_EDIT_BOOKLETMARGINLEFT      1062
#define IDC_RADIO_TDUP                  1062
#define IDC_RADIO_LABEL_TITLESTRAIGHT   1063
#define IDC_RADIO_TDDOWN                1063
#define IDC_RADIO_LABEL_TRACKROUND      1064
#define IDC_RADIO_LABEL_TRACKSTRAIGHT   1065
#define IDC_RADIO_ROUNDTEXT             1065
#define IDC_CHECK_LABEL_TRACKS          1066
#define IDC_RADIO_STRAIGHTTEXT          1066
#define IDC_CHECK_LABEL_TRACKGROUPS     1067
#define IDC_COMBO_LABEL_TITLECENTER     1068
#define IDC_COMBO_LABEL_TRACKCENTER     1069
#define IDC_LIST_DRIVES                 1069
#define IDC_TAB                         1070
#define IDC_EDIT_COVERMARGINTOP         1074
#define IDC_EDIT_COVERBACKMARGINTOP     1075
#define IDC_COMBO_PRINTCOVERBACKTOGETHER 1076
#define IDC_EDIT_INLAYMARGINTOP         1077
#define IDC_COMBO_PRINTINLAYTOGETHER    1078
#define IDC_EDIT_LABELMARGINTOP         1079
#define IDC_COMBO_COVERLABELTYPE        1080
#define IDC_COMBO_COVERBACKLABELTYPE    1081
#define IDC_COMBO_LABELLABELTYPE        1082
#define IDC_COMBO_INLAYLABELTYPE        1083
#define IDC_RADIO_COVERBACK_PORTRAIT    1084
#define IDC_RADIO_COVERBACK_LANDSCAPE   1085
#define IDC_RADIO_COVER_PORTRAIT        1086
#define IDC_DEGM_COVER                  1086
#define IDC_RADIO_COVER_LANDSCAPE       1087
#define IDC_DEGM_LABEL                  1087
#define IDC_RADIO_INLAY_PORTRAIT        1088
#define IDC_DEGM_BACK                   1088
#define IDC_RADIO_INLAY_LANDSCAPE       1089
#define IDC_DEGM_INLAY                  1089
#define IDC_RADIO_LABEL_PORTRAIT        1090
#define IDC_SPIN_DEGCOVER               1090
#define IDC_RADIO_LABEL_LANDSCAPE       1091
#define IDC_SPIN_DEGBACK                1091
#define IDC_SPIN_DEGLABEL               1092
#define IDC_CHECK_2LABELS               1092
#define IDC_SPIN_DEGINLAY               1093
#define IDC_BUTTON_TRANSPARENTCOLOR     1093
#define IDC_EDIT_BOOKLETMARGINTOP       1093
#define IDC_BUTTON_REMOVETRANSPARENT    1094
#define IDC_RADIO_BOOKLET_PORTRAIT      1094
#define IDC_STATIC_TRANSPARENT          1095
#define IDC_RADIO_BOOKLET_LANDSCAPE     1095
#define IDC_STATIC_ANIMATION            1096
#define IDC_LIST_TITLES                 1097
#define IDC_BUTTON_CANCELDOWNLOAD       1098
#define IDC_CHECK_INLAY_SHOWTITLES      1099
#define IDC_CHECK_INLAY_SHOWSIDEBARS    1100
#define IDC_CHECK_SHOWPAGENUMS          1100
#define IDC_CHECK1                      1101
#define IDC_CHECK_LABEL_SHOWTITLES      1101
#define IDC_CHECK_USEGRADIENTFILL       1101
#define IDC_CHECK_SHOWTRACKS            1101
#define IDC_STATIC_VERSION              1102
#define IDC_CHECK_PROGVERSION           1103
#define IDC_BUTTON_SKIP                 1105
#define IDC_RICHEDIT                    1106
#define IDC_BUTTON_PRINTTEST            1107
#define IDC_BUTTON_CHECKNEWLIBS         1109
#define IDC_LIST1                       1110
#define IDC_LIST2                       1111
#define IDC_RICHEDIT_TITLE              1113
#define IDC_STATIC_BKCOLOR              1114
#define IDC_DEGM                        1115
#define IDC_EDIT_DEG                    1116
#define IDC_SPIN_DEG                    1117
#define IDC_BUTTON_BKCOLOR              1118
#define IDC_BUTTON_BKCOLOR2             1119
#define IDC_RADIO_ALPHAFORMAT_DARKEN    1122
#define IDC_RADIO_ALPHAFORMAT_LIGHTEN   1123
#define IDC_SLIDER_OPACITY              1124
#define IDC_BUTTON_DELETE               1125
#define IDC_BUTTON_LABELTRACKTITLECENTER 1127
#define IDC_BUTTON_HALIGN_CENTER        1128
#define IDC_CHECK_TITLE_SHOW            1129
#define IDC_CHECK_SHOWTITLES            1129
#define IDC_CHECK_SHOWGROUPINGS         1130
#define IDC_RADIO_TITLEMARGINLEFT       1131
#define IDC_RADIO_VATOP                 1131
#define IDC_RADIO_TITLEMARGINRIGHT      1132
#define IDC_RADIO_VABOTTOM              1132
#define IDC_RADIO_TITLEMARGINCENTER     1133
#define IDC_RADIO_VACENTER              1133
#define IDC_EDIT_TITLEHALIGNLEFT        1134
#define IDC_EDIT_VATOP                  1134
#define IDC_EDIT_TITLEHALIGNRIGHT       1135
#define IDC_EDIT_VABOTTOM               1135
#define IDC_EDIT_TITLEVALIGNTOP         1136
#define IDC_EDIT_TITLEVALIGNHEIGHT      1137
#define IDC_STATIC_TOP                  1138
#define IDC_STATIC_HEIGHT               1139
#define IDC_STATIC_CM1                  1140
#define IDC_STATIC_CM2                  1141
#define IDC_GROUP_HORZ                  1142
#define IDC_GROUP_VERT                  1143
#define IDC_STATIC_CREDITS              1148
#define IDC_BUTTON_PRINTPOWER           1149
#define IDC_BUTTON_FUNPRINT             1150
#define IDS_BROWSER_BKALPHA             1661
#define IDS_CREDITS                     2000
#define IDC_CHECK_INCLUDECUTLINESWHENPRINGING 2222
#define IDS_COL_TRACKS                  10000
#define IDS_COL_LENGTH                  10001
#define IDS_COL_TITLE                   10002
#define IDS_COL_REMARKS                 10003
#define IDS_FORMAT_TRACK                10004
#define IDS_COVER                       10005
#define IDS_BACK                        10006
#define IDS_INLAY                       10007
#define IDS_LABEL                       10008
#define IDS_NAME                        10009
#define IDS_TRACK_DISPLAY               11000
#define IDS_TRACK_LENGTH                11001
#define IDS_TRACK_TITLE                 11002
#define IDS_TRACK_REMARKS               11003
#define IDS_TRACK_ALIGN                 11100
#define IDS_STRING11101                 11101
#define IDS_STRING11102                 11102
#define IDS_STRING11103                 11103
#define IDS_TRACK_DISPLAY_FORMATTING    11200
#define IDS_STRING11201                 11201
#define IDS_STRING11202                 11202
#define IDS_STRING11203                 11203
#define IDS_STRING11204                 11204
#define IDS_STRING11205                 11205
#define IDS_TRACK_LENGTH_FORMATTING     11300
#define IDS_STRING11301                 11301
#define IDS_STRING11302                 11302
#define ID_BUTTON_MINIMIZE              32600
#define ID_BUTTON_RESTORE               32601
#define ID_BUTTON_CLOSE                 32602
#define ID_ADDGROUPING                  32771
#define ID_DELETEGROUPING               32772
#define ID_TOOLS_ADDIMAGE               32772
#define ID_PROPERTIES                   32773
#define ID_STYLETEMPLATE                32774
#define ID_ZOOMOUT                      32775
#define ID_ZOOMIN                       32776
#define ID_TOOLS_ADDTEXT                32777
#define ID_SHOWINLAY                    32784
#define ID_SHOWCOVER                    32786
#define ID_SHOWLABEL                    32789
#define ID_SHOWBACK                     32790
#define ID_DELETETRACK                  32791
#define ID_FILE_PROGRAMOPTIONS          32792
#define ID_CHECKVERSION                 32793
#define ID_BKIMG_SCAN                   32794
#define ID_BKIMG_LISTWEB                32795
#define ID_BKIMG_SEARCHWEB              32796
#define ID_BKIMG_IMAGE                  32797
#define ID_FILE_NEW_EMPTYPROJECT        32798
#define ID_FILE_SAVE_AS_IMAGE           32915
#define ID_FILE_NEW_WIZARD              32799
#define ID_FILE_NEW_LISTWEB             32802
#define ID_FILE_NEW_SEARCHWEB           32803
#define ID_SHOWBOOKLET                  32805
#define ID_BROWSE_SEARCH                32806
#define ID_BROWSE_APPLY                 32807
#define ID_BROWSE_LIST                  32808
#define ID_VIEW_STYLES                  32809
#define ID_ANSICHT_COVERBROWSER         32810
#define ID_VIEW_COVERBROWSER            32811
#define ID_BROWSE_IMAGE                 32812
#define ID_BROWSE_BKTEXTURE             32814
#define ID_BROWSE_BKALPHA               32815
#define ID_BROWSE_WEB                   32816
#define ID_VIEW_LEFTPANEL               32818
#define ID_VIEW_LYRICSBROWSER           32819
#define ID_LBROWSE_SEARCH               32821
#define ID_LBROWSE_LIST                 32822
#define ID_RTFF_BOLD                    32823
#define ID_RTFF_ITALIC                  32824
#define ID_RTFF_UNDERLINE               32825
#define ID_RTFF_ALIGNLEFT               32826
#define ID_RTFF_ALIGNCENTER             32827
#define ID_RTFF_ALIGNRIGHT              32828
#define ID_RTFF_STRIKETHRU              32830
#define ID_RTFF_SUP                     32831
#define ID_RTFF_SUB                     32832
#define ID_RTFF_FONT                    32833
#define ID_RTFF_FONTSIZE                32834
#define ID_RTFF_COLOR                   32835
#define ID_RTFF_UNDERLINE_DOT           32836
#define ID_RTFF_BKCOLOR                 32838
#define ID_RTFF_BULLETS                 32842
#define ID_RTFF_BORDER                  32843
#define ID_RTFF_PAGEBREAK               32844
#define ID_FILE_NEW_IMPORTM3U           32845
#define ID_RTFF_BORDER_LEFT             32849
#define ID_RTFF_BORDER_RIGHT            32850
#define ID_RTFF_BORDER_TOP              32851
#define ID_RTFF_BORDER_BOTTOM           32852
#define ID_RTFF_BORDER_INSIDE           32853
#define ID_RTFF_BORDER_OUTSIDE          32854
#define ID_RTFF_BULLETS_NONE            32855
#define ID_RTFF_BULLETS_BULLET          32856
#define ID_RTFF_BULLETS_123             32857
#define ID_RTFF_BULLETS_LOWER           32858
#define ID_RTFF_BULLETS_UPPER           32859
#define ID_RTFF_BULLETS_ROMLOWER        32860
#define ID_RTFF_BULLETS_ROMUPPER        32861
#define ID_TOOLS_ADDBARCODE             32901
#define ID__BARCODEPROPERTIES           32910
#define ID_FILE_LIGHTSCRIBE             33000
#define ID_FILE_PRINT2                  57608
#define ID_FILE_PRINT_PREVIEW2          57610
#define ID_FILE_PRINT3                  57611
#define ID_FILE_PRINT_PREVIEW3          57612

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        230
#define _APS_NEXT_COMMAND_VALUE         32799
#define _APS_NEXT_CONTROL_VALUE         1036
#define _APS_NEXT_SYMED_VALUE           128
#endif
#endif
